### ISSUE TITLE
Allocation between boats and strata

### ISSUE THREAD

**Issue by Ned-Laman-NOAA** [afsc-gap-products/Survey-Planning#1]
Apply sampling design and allocation code to pick and assign stations to vessels

**Comment by zoyafuso-NOAA** [comment]
[Discussion](https://docs.google.com/document/d/1SfOtuP3632TT5Xb5Ef0rmkWx4LLKEiJp9hJleWxh6lI/edit) about how to incorporate new unvisited stations 

[R package](https://github.com/afsc-gap-products/AIGOASurveyPlanning) that houses the `goa.planning()` function that allocates stations to strata and vessel.

[Repo](https://github.com/zoyafuso-NOAA/AI_planning_stations) that runs the code and outputs station allocation spreadsheet. 

Station allocation spreadsheet delivered to Mark Zimmerman and Paul von Szalay 1/27/2022

**Comment by zoyafuso-NOAA** [comment]
What else do we need to do for this task?

**Comment by MargaretSiple-NOAA** [comment]
@Ned-Laman-NOAA is there anything else we need to do here?

**Comment by Ned-Laman-NOAA** [comment]
Sorry! Got confused for a second. This one is done. Stations have been assigned to strata and to vessels.
I was thinking about Special Project allocation to vessels which is still ToDo.
