### ISSUE TITLE
Survey stations

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/Survey-Planning#16]

**Comment by bethanyriggle** [comment]
Survey stations added to 2022 charts, needing to work with @MargaretSiple-NOAA and @coleary-noaa to match up station shapes and colors with the GLOBE ones.

**Comment by bethanyriggle** [comment]
ArcMap Symbols being used:
![ArcMap Legend](https://user-images.githubusercontent.com/70727383/158650479-e1045276-86a8-4655-80ee-432cacb3a996.png)
 
These are from the 2020 charts, but red triangles will be Alaska Provider, and blue squares will be Vessel 2.

Met with @MargaretSiple-NOAA on 03/14 to get on same page with symbols and colors for ArcMap and GLOBE charts.

**Comment by MargaretSiple-NOAA** [comment]
Thank you Bethany!! This is super helpful. I am figuring out today how to do the Globe highly-visible versions of both of those. Will definitely match the symbols and may made red--> hot pink and dark blue--> bright turquoise because of the black background in Globe.

**Comment by MargaretSiple-NOAA** [comment]
OK, there is now an AI stations file on the G Drive that has the high-contrast versions of this scheme. It's called 
G:\ALEUTIAN\AI 2022\Files for Boats\Globe\Marks\AI_stations_2022_mcs_colorfix.mdb

| Vessel | Color in Arc| Color in Globe (Globe color code) | Symbol in Arc and Globe (symbol code) |
| ----------- | ----------- | ----------- | ----------- |
| Alaska Provider | Red | Hot pink (13) |🔺 (0) |
| Vessel 2 | Blue | Hot blue (11) | 🟦 (3) |

It looks like this in Globe:
![HighContrastStations](https://user-images.githubusercontent.com/73858992/158701023-e9ea2f98-40e2-401d-8410-ac40af79f8e5.PNG)

If this looks good, I think you can close this issue?

**Comment by bethanyriggle** [comment]
Awesome! This looks great to me! I will consult with Mark to make sure we are good to close this issue.

**Comment by bethanyriggle** [comment]
Created PDF versions of the charts, and placed them in G Drive. G:\ALEUTIAN\AI 2022\ArcGIS\2022_Charts.zip\2022_Charts

Still need to fix a few things regarding the notes about the 10 stations needing to be found, and alter the red notes on charts 1 and 2 about finding new stations.

**Comment by bethanyriggle** [comment]
10 survey stations needing to be found have had notes added to the charts, and are saved in the G Drive. 

G:\ALEUTIAN\AI 2022\ArcGIS\2022_Charts.zip\2022_Charts

Since all stations have been added to the charts, along with the notes for the 10 new ones to be found, I am officially closing the issue.
