### ISSUE TITLE
Review of proposals

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/Survey-Planning#26]

**Comment by Conrathcl** [comment]
I started a table[ here](https://docs.google.com/spreadsheets/d/1br8esdbZYswRgeTI5EKr7PIXhePW4nCW/edit?usp=sharing&ouid=105279028397081025832&rtpof=true&sd=true) to keep track of special project requests . It is a starting place for the discussion, scroll to the far right columns for a place to add your thoughts, notes, and action items.  Several projects are repeaters so have more info/notes from last year that I decided to carry forward. I wanted to get this out this morning, but it is just a rough start.  

I chatted with Nancy about getting an easier to read version of the information that is in the excel file.  I am not sure if this will happen or not - stay tuned. 

There are a number of projects with either supplementary information or detailed instructions that were sent directly to Nancy.  I am working on a list to email her about; I would like to consolidate it to one email if possible (she is busy!).  I am also working on a list of database queries that will help aid in our evaluation of these projects.

**Comment by Ned-Laman-NOAA** [comment]
Thanks, Christina. This is outstanding! I've made it about halfway through my personal ranking system on these projects and had noted some of the things you are already working on (e.g., supplementary information, assessing asks from RACEBase perspective, etc.) so thank for being right on top of this. I'm looking forward to our conversation tomorrow.

**Comment by Conrathcl** [comment]
Shared google drive folder with special project materials [here](https://drive.google.com/drive/folders/1g2MFkv-D_FSx1ohAJS2cKaF25ciLuFB6?usp=sharing).  Thanks Ned for passing along the files from Nancy.

**Comment by Ned-Laman-NOAA** [comment]
Thanks, Christina.
I should've thought to put them in our folder or share them here in GitHub.
...still learning!

**Comment by Ned-Laman-NOAA** [comment]
PS - I've spoken with Shawn Russell about the mooring project and have sent him the additional information to help us evaluate whether that ask is doable from our boats.

**Comment by Conrathcl** [comment]
Hi All,

Quick status update: 
We have heard back from all the PIs with clarifying information (captured in the notes + spreadsheet).  A summary of the queries is on the second sheet of the [evaluation file](https://docs.google.com/spreadsheets/d/1br8esdbZYswRgeTI5EKr7PIXhePW4nCW/edit?usp=sharing&ouid=105279028397081025832&rtpof=true&sd=true).  I don't think there was anything to be overly concerned about in the queries, except the crab numbers were a bit higher than I would have thought.  I tried to get all of the information into the spread sheet but most of it is also captured in the notes.  I put Ned's estimate of time on the sheet and made a quick evaluation of the chemicals/freezer needs. I think the only projects that may need extra chemicals are my own and possibly Sean's project. We can finalize that after we have come to a final decision on all the projects. 

Remaining action items: 
- List of special project coordinates for survey maps/globe charts (Stone project, mooring?, any others?).  I will get a sheet started by next week with coordinates. 
- Finalize text and contact R. Clark about gastropod request (text [here](https://docs.google.com/document/d/1_Q7v01NGy4AYkJjrF6HIX7OB8XZjUo-R/edit?usp=sharing&ouid=105279028397081025832&rtpof=true&sd=true) if anyone wants to review, please feel free to edit!)
- Review mooring information/request? 
- Review division priority rankings when we receive them.  
- Discuss crab lengths ---- are we hand writing the data? or is there a better way?  I think this may be a bigger effort than I originally thought, so it might be good to discuss how to best work it into survey operations.

**Comment by Ned-Laman-NOAA** [comment]
Thanks, Christina.
This all looks right on track and thanks for summarizing the queries and responses so far.
On the remaining action items:
I plan to contact the mooring project people to ask if they can supply "quick release for the crane hook and a long pole gaff for deployment and retrieval" per Shawn Russell's recommendation. I don't recall if I communicated it to you, but Shawn thought this mooring project was doable from a charter boat if we had those additional pieces of equipment.
Per the crab lengths. What specifically makes you think this "may be a bigger effort"? I thought I read they planned for us to handwrite these lengths which has the potential to mean 2 people working on this when there are lots of GKCs.

**Comment by Conrathcl** [comment]
Thanks Ned, good point on the crab lengths - I was surprised by how many tows they were in over the past few surveys but mostly in small numbers.  On further reflection, I think we can knock that off the 'to do' list.  

The deadline for this task is tomorrow - have you received the division priority rankings?

**Comment by Ned-Laman-NOAA** [comment]
Sounds like we are coming to the same conclusions about the crab lengths.
I was just starting to review the Division rankings [here](https://docs.google.com/spreadsheets/d/1svA3mD8nV3nRnkmIF8MZqeIC4tLpjn1ltTBVjvYoB1k/edit?usp=sharing). 
Since we didn't reject any projects out of hand, I don't see any conflicts with the Division rankings. 
It did seem odd that Ingrid's flatfish genomics project got labelled Mission Critical but wasn't ranked.

**Comment by Conrathcl** [comment]
Thanks Ned, 

It looks like the mooring project ranked very high (#one). I'm wanting to clarify that the parts of this work that require putting things over the side of the boat and/or retrieving them will be handled by the vessel personnel? And that this work is acceptable to the boat personnel as well as within the parameters of the contracts. I know that Shawn seemed to think it would be no problem. Similar question for Wes's project. 

It sounds like we are accepting all the projects. Do we need any additional discussion? or?

Is there additional information to put together or evaluate to assist in the assigning the projects to vessels?  I did a quick evaluation of freezer space/boxes. Do we need to wait until we know the second vessel before we dive into that?

Not sure if we are in a holding pattern place or a pushing forward place given how quickly the deadlines are approaching.

**Comment by Ned-Laman-NOAA** [comment]
These are all great questions, Christina.
I'm with you that I want to have eye-to-eye discussions with the vessel captains (both) where these over-the-side projects are concerned. That puts us in a holding pattern for Wes' project since it will have to be on boat 2 to accommodate balancing the extra vessel days requested for yours and his projects. Those extra vessel days are also a discussion with the vessels. In that regard, both you and Wes will need to consider e.g., the vessel refusing or only accepting one day.
It does sound like we are accepting all projects, but yours, Wes', and the mooring project depend on the skippers being willing to take on the over-the-side projects, extra days, and, in the case Wes' project, working with him to figure out how best to launch and retrieve his water sampler.
I think we can start thinking about distributing special projects to boats given the caveats above and the likely fact that no second vessel we get will have more freezer space than the Alaska Provider!
We can talk about this in our staff meeting today as well.

**Comment by Ned-Laman-NOAA** [comment]
Learned some more about the mooring project:
The first thing I learned is that Jerry discussed with Catherine and Robyn Angliss the possibility that the acoustic release on the old mooring fails. If that happens, their recommendation was to drag a grapple for the old mooring! That would be a hard No in my opinion. However, Jerry has also indicated that they will be reasonable and even entertained the option at one point of simply deploying a second mooring without retrieving the first. Short version is that once we have confirmation from the AKP that we can do this mooring project from their vessel (Jerry is pretty convinced they will allow it), we should have a conversation with the requesters about failure points and what we are able to do in those cases.

**Comment by Conrathcl** [comment]
Emily and Liz have a form for setting up a placard for special projects.  I have a draft of the text for that [here](https://docs.google.com/spreadsheets/d/1g-yICVQsucBHSX9JKAIOXQ-FEvJacRLWKGheCM262yI/edit?usp=sharing) in case anyone wants to review/edit. I'll submit as soon as we have a second vessel and have allocated projects between boats.  

Question for @Ned-Laman-NOAA : we are also going to want some tally sheet placards.  Last year Wayne did the placards.  Is that something we take care of? Is it in Nancy's purview? or?  

I've added the supplemental information to the text provided by Emily and Liz for each project, so those will be ready for inclusion in the ops plan as soon as the boat allocation is finished.

**Comment by Ned-Laman-NOAA** [comment]
While we don't know the name of the other vessel, I think we can do the vessel allocation now. We might not be able to print the placards, but we will need to put things in the right gear piles for the vans in the next couple of weeks. Which of these projects are for both vessels and which are on just one? Can you add that to the text you linked above?

**Comment by nwraring** [comment]
@Conrathcl , I will be doing the placards. I'm get this started next week.

**Comment by Conrathcl** [comment]
Thanks @nwraring there are a number of projects that would benefit from having a tally sheet on deck, let me know if you want me to help with this effort.

I'm not the lead on the vessel allocation, so I was waiting before diving in.  I will take a first crack at it today and add it to this [sheet](https://docs.google.com/spreadsheets/d/1br8esdbZYswRgeTI5EKr7PIXhePW4nCW/edit?usp=sharing&ouid=105279028397081025832&rtpof=true&sd=true) as not all projects need to be on the deck placard (e.g. mooring, Larson, Conrath).
