### ISSUE TITLE
Travel plans

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/Survey-Planning#34]
Adding check boxes here to get better resolution for tasks. 

Travel requests drafted and sent to Ned (@MargaretSiple-NOAA and @SarahFriedman-NOAA ):

- [x] Travel requests for Leg 1
- [x] Travel requests for Leg 2
- [x] Travel requests for Leg 3

Travel requests signed and sent to nmfs.afsc.race.admin@noaa.gov  (@Ned-Laman-NOAA ):

- [x] Leg 1
- [x] Leg 2
- [x] Leg 3

Send emails (@MargaretSiple-NOAA ):

- [x] April 2: Timekeeping info, E2 status, port guides
- [x] April 7: Timekeeping, gmail authentication, health assessments (general COVID update)
- [ ] May 3: SIP guides
- [x] May 14: Request travel itineraries from all staff

**Comment by MargaretSiple-NOAA** [comment]
@bethanyriggle Can you confirm whether the dates and staff on the schedule that Nate sent March 8th are set in stone? If so, we can get started on travel plans for everyone. I may have to talk to @nwraring and Ned about which airlines and accommodations are the ones to use. 

Thank you Sarah for reminding me to get on this!

**Comment by bethanyriggle** [comment]
@MargaretSiple-NOAA We just confirmed dates with the AK Provider, and made a couple of date changes, so I can forward you the newest staffing spreadsheet. We have not secured a second vessel, though, so we can't solidify dates for those personnel assigned to Vessel 2. Alaska airlines and Ravn will be the airlines for Dutch Harbor travel, and Alaska airlines will be the only one for Adak travel. Flights only go to Adak on Wednesdays and Saturdays, which are reflected in the dates for starting the reduced contact period and leg changes. I believe they are still working on lodging in Adak. @Ned-Laman-NOAA will have to chime in here for confirmation on everything in regards to booking travel.

**Comment by Ned-Laman-NOAA** [comment]
hi all - travel plans have been on my daily list for a week now so we must all be thinking along the same lines. 
@MargaretSiple-NOAA - lets you and I get together and start setting up Leg 1 travel. At the moment that means we need to build some multi-travel Return-to-Work (RTOW) packages and travel requests. I still need to work out some of the details of that and it might be wise for us to do it together so we both know. As for Adak legs, we have a little time and once Leg 1 is in the pipeline we can start those conversations with our travel arrangers and Michael.

**Comment by MargaretSiple-NOAA** [comment]
Hi Ned et al, 
I was just looking back through all my emails from last survey season and saw all the emails I sent folks about sea bag drop off, forms, and a bunch of other stuff. Please forgive me for not checking this earlier. I will check sea bag drop off dates with Kevin (?) and will tag Ned on the first email draft so we can agree on when it should be sent.

Here is a brief summary of the type of stuff I sent last year:
March 20-ish: Check trainings with staff and observers: coldwater training, medical emergencies at sea. Send packing list and "working conditions" docs.
March 23: Email about E2 profiles (confirming that staff have them and know who their travel arrangers are)
March 24: Email (from Wayne) about sea bag drop-off
April 2: Timekeeping info, E2 status, port guides
April 7: Timekeeping, gmail authentication, health assessments (general COVID update)
May 3: SIP guides
May 14: Request travel itineraries from all staff

I've put all these emails and the attachments I sent in [this Google Drive folder](https://drive.google.com/drive/folders/1YdWV29UO2WtWbXU9A5Oe_QR5oEveBYyu?usp=sharing). Soon (ish) I'll request Ned's input on what text needs to change for the emails.

**Comment by MargaretSiple-NOAA** [comment]
As of today, I have filled out travel requests for Leg 1 staff on both vessels, including Nate and Bethany who are staying for two total legs 🛫 . Travel Requests are stored [here](https://drive.google.com/drive/folders/1XN9fBpNjic0OOvXAZ5zWkQPfbCTmq0k7?usp=sharing).

**Comment by SarahFriedman-NOAA** [comment]
Travel requests are completed for all legs with the updated survey dates! All are in the google drive folder Megsie linked above.

**Comment by nwraring** [comment]
@bethanyriggle 
Hey all. I'm not sure if this is something we have to deal with this year or not. In past years we have had  to get paperwork from anyone that was a volunteer regarding bank account info so that the per diem could get deposited even if they weren't getting a paycheck. I'm not sure if this is something that we would still do for Albi, Mabel  or Katie. I only collected these one year. Other years I think it was handled by Wayne or Ned but not sure. Maybe we don't need to do this or it's already been done. Jut wanted to ask the question and keep it as a reminder. Any thoughts?
Nate

**Comment by Ned-Laman-NOAA** [comment]
I think that we do need this paperwork for certain individuals, though I'm not positive I know who they are at this point other than to say I'm pretty sure that Katie and Mabel wouldn't be them since they are already inside the NOAA firewall as FTEs. Albi might be one who needs the form, but maybe that's another question we can push toward Martin Dorn as he works with Albi and UW to get Albi's travel sorted? Who else do we have who isn't contract of FTE?

**Comment by nwraring** [comment]
Since observers and IPHC folks handle thier travel separately they wouldn't get per diem. Stomach lab contractors have their own deal. Jeremy was out with us last year so his paperwork is probably already un unless it needs to be re-submitted. I think that's everyone.

**Comment by Ned-Laman-NOAA** [comment]
OK, so Megsie has already been in contact with Martin about Albi. Let's see what she can turn up. Cecilia was in Albi's position just a couple of years ago so she probably recalls some details that could help. Can you drop her a note?

**Comment by nwraring** [comment]
will do.

**Comment by nwraring** [comment]
@coleary-noaa 
Hey Cecilia. We're trying to figure out what Albi needs to do in order to be able to turn in expenses for travel and get per diem. Do you recall what paperwork you had to submit when you were doing a post-doc and went out on the survey?
Thanks,
Nate

**Comment by MargaretSiple-NOAA** [comment]
Hi team-- I've been in touch with Albi, Martin, and André about his travel arrangements and I think he has all the info he needs to get it set up. I'm pretty sure that any account paying his per diem is set up at UW not at NOAA. Any which way, I think we have what we need, unless Albi has contacted you today asking for further help.

**Comment by nwraring** [comment]
Thanks for looking into that Megsie! I haven't heard from Albi but I'll
keep an eye out. Have a great weekend.

**Comment by Ned-Laman-NOAA** [comment]
Thanks, Megsie and Nate.
It is a great help to me and to the survey that you are do on top of this!

**Comment by coleary-noaa** [comment]
I sent more details to Ned, Megsie, Sarah on 18 April in an email requesting this info, but yes, if you are a contractor/postdoc at UW, all your forms and travel arrangement are through UW and a UW spending account with my grant money was used. I do not know how it worked behind the scenes between UW and NOAA (Andre would know).

**Comment by nwraring** [comment]
Thanks Cecilia.

**Comment by MargaretSiple-NOAA** [comment]
Albi is all taken care of -- he has plane tickets in hand and has reservations for his SIP. The flights are entered in our Flights tab. All that remains to do is:

- [x] Distribute COVID antigen tests to remaining staff
- [ ] Confirm that all itineraries are in Files for Boats

**Comment by Ned-Laman-NOAA** [comment]
Congratulations! Getting to this point represents a lot of work all y'all.
