### ISSUE TITLE
Station Progress Spreadsheet

### ISSUE THREAD

**Issue by Ned-Laman-NOAA** [afsc-gap-products/Survey-Planning#4]
This is the pre-printed physical log of stations sampled that the FPC fills out on the bridge

- [ ] Ned/Nate

**Comment by bethanyriggle** [comment]
Blerg

**Comment by zoyafuso-NOAA** [comment]
From @Ned-Laman-NOAA :

Can a station dropping tool take day of survey into account?
What I'm thinking is that on your first fishing day, you have the entire Aleutian chain to distribute your dropped stations across. On a day mid way through the survey, half of the stations picked to drop have already been sampled, right?
I'm not really sure that this is a tractable problem to solve with code, but now I'm wondering what I would do in that situation.
Thoughts?

**Comment by zoyafuso-NOAA** [comment]
Hi @Ned-Laman-NOAA,

Yes, this is the drawback of the station dropping protocol I proposed. Correct, if the decision to drop stations is done at the halfway point, half of the stations prioritized to drop may have already been sampled. One workaround would be to develop code that conducts the Neyman allocation conditional on the strata that have not been sampled yet, e.g., you finish with the strata in the SBS and EAI and then conduct the Neyman allocation on just strata in the WAI and CAI. However, I'm not sure of the consequences of doing this on the allocation; it is a different objective to conduct an optimal allocation of stations across strata given that some of the strata have been at least partially sampled. And I'm concerned whether doing so would potentially add new stations to the remaining/unsampled strata while at the same time reducing stations in other strata. So I wouldn't recommend that without more investigation. 

In that situation, there are at least two scenarios that could happen: 

1)  You're on stratum A and finished 9/10 stations. You make the decision to drop 10 stations and one of the stations in that list is in stratum A and that station was already sampled. The decision would be to switch that dropped station with the station in stratum A that wasn't sampled yet. This is the easy situation and could probably be forecasted in the very short term.

2) You've completed all stations in the SBS and make the decision to drop 10 stations. Two of the dropped stations in that list of the first 10 stations are in the SBS and have already been sampled.  The decision would be to randomly draw two stations from the list of the next 10 dropped stations. This is not ideal of course as it is not exactly consistent with what the optimal allocation would be but it definitely is close.

**Comment by Ned-Laman-NOAA** [comment]
@zoyafuso-NOAA,
This is just a thought experiment for this year, but a good one. This could play out in the Gulf as well so this isn't in a vacuum.
I arrived at your conclusion #2 as well. This could be done thru human intervention (FPC coin flipping or whatever) rather than programmatically and I think would still fit within the spirit of what you've already established with the station dropping tool

**Comment by zoyafuso-NOAA** [comment]
Station dropping worksheet and rationale moved to: G:\ALEUTIAN\AI 2022\Files for Boats\Station Dropping Tool

**Comment by Ned-Laman-NOAA** [comment]
Thanks, Zack.

**Comment by Ned-Laman-NOAA** [comment]
Hi Zack,
Another piece of this task that we need to produce (or reproduce) is the tool that allows the FPCs (in consultation with folks back here on the beach) to determine if they have fallen far enough behind expected progress that we need to consider dropping a set of the identified stations. I think we can pretty easily refurbish one of the existing Excel versions of this (e.g., G:\ALEUTIAN\AI 2018\Files for boats\Station.Drop). Did we already talk about this aspect of the task? If not, let's chat soon.

**Comment by zoyafuso-NOAA** [comment]
So I essentially took that station dropping decision worksheet from 2018, changed the dates and names and saved it to the 2022 folder (G:\ALEUTIAN\AI 2022\Files for Boats\Station Dropping Tool). The second vessel is still V2 for now. I'm not sure what else should be done for that.

**Comment by Ned-Laman-NOAA** [comment]
That should do the trick, Zack. I think we may need to go into the "expected" worksheets on each and adjust the dates there, but I can't recall just how that Excel sheet works so don't know how important that step is.
