### ISSUE TITLE
GBL Request (3 months before arrival date in Dutch Harbor)

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/Survey-Planning#58]

**Comment by Ned-Laman-NOAA** [comment]
[NOAA Form 42-15, Bill of Lading Request-94-nb2016.pdf](https://github.com/afsc-gap-products/Survey-Planning/files/8100461/NOAA.Form.42-15.Bill.of.Lading.Request-94-nb2016.pdf)

**Comment by bethanyriggle** [comment]
@Ned-Laman-NOAA, @nwraring and I met with Rebecca and Nicole on Friday, and Rebecca informed us that she has never had to fill this out for the survey, and usually RSST has handled this. Might be something to investigate further?

**Comment by Ned-Laman-NOAA** [comment]
I will look into this and get back to you.

**Comment by Ned-Laman-NOAA** [comment]
I heard from Gary McMurrin that Joanna typically has the duty for submitting the GBL for the containers and the net loft submits one for the flats that take the nets. 
Joanna should be in our staff meeting tomorrow so let's confirm with her that she agrees with Gary's assessment and then we could consider modifying this task in the Task List to indicate RSST is responsible or perhaps we remove it from our list?

**Comment by Ned-Laman-NOAA** [comment]
Closed. RSST submitted GBL.
