### ISSUE TITLE
Update Survey Stations

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/Survey-Planning#8]
Cecilia/Ned/Megsie's instructions for updating Globe files are [here](https://docs.google.com/document/d/1Dyt0soCwV0SBIY6bk4szMGlNDwGNGxQL/edit?usp=sharing&ouid=111519802483611531993&rtpof=true&sd=true). 

Products from this process:
1. Station list for the year in Access and entered in Globe
2. Survey grid in Access, entered in Globe, and output in ArcGIS format for Mark

**Comment by coleary-noaa** [comment]
Received AI 2022 station list from Zack, completed conversion to Globe file and loaded on to G drive G:\ALEUTIAN\AI 2022\Files for Boats\Globe\Marks\AI_stations_2022.mdb and on both Globe computers.

**Comment by MargaretSiple-NOAA** [comment]
Confirmed that the doc above (on G Drive) is the same set of stations sent out by Ned on 2/28; "AIallocation420.xlsx". The header of the table looks like this:

![image](https://user-images.githubusercontent.com/73858992/156069742-850ceb4a-eba1-49c4-9ddb-5d500045af55.png)

**Comment by Ned-Laman-NOAA** [comment]
Outstanding!
