### ISSUE TITLE
Update Old Tow Paths

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/Survey-Planning#9]

**Comment by coleary-noaa** [comment]
started task & are creating files. Access 2010 wasn't installed on one Globe computer and Gary is working on that.

**Comment by coleary-noaa** [comment]
Completed and loaded on to G drive G:\ALEUTIAN\AI 2022\Files for Boats\Globe\Lines\globe_paths_2022.mdb and loaded on both Globe computers.

**Comment by MargaretSiple-NOAA** [comment]
For future reference, here is where the files on the Globe 990 computer came from:

## Lines files
globe_paths_2022.mdb - created from instructions and compared w Cecilia file
New_rookery_lines_2021.mdb - copied from G:\GOA\GOA 2021\Files for boats\Globe\Lines
survey_grid_2022.mdb - created from instructions and compared w Cecilia file
Survey2018SSLhapc areas.mdb - copied from G:\ALEUTIAN\AI 2018\Files for boats\Globe\Lines
SurveyTowPaths1980through2016.mdb - copied from G:\ALEUTIAN\AI 2018\Files for boats\Globe\Lines

## Marks files
AI_stations_2022.mdb - created from instructions and compared w Cecilia file
globe_starts_2022.mdb - created from instructions and compared to your mdb
NoTransitZones.mdb - copied from G:\ALEUTIAN\AI 2018\Files for boats\Globe\Marks
SSI_3nm_Buffer_2021.mdb - copied from G:\GOA\GOA 2021\Files for boats\Globe\Marks
